### ISSUE TITLE
Research existing open-source chat bots and Natural Language Processing solutions

### ISSUE THREAD

**Issue by brylie** [apinf/apinf-bot#12]
In order to accellerate this project development, we can build on an existing open-source chatbot. This will give us a foundation on which to build Apinf specific features.

# Task
- [ ] Research one or more chat bot and NLP solutions
- [ ] Identify integration priorities, such as desired platform
- [ ] Choose one or more candidate chat bot solutions for initial testing

**Comment by brylie** [comment]
[HUBOT](https://hubot.github.com/) is one possible platform, on which to base this project. Hubot is extensible, and already has many [community contributed modules](https://www.npmjs.com/search?q=hubot).

**Comment by kyyberi** [comment]
+1

**Comment by kyyberi** [comment]
http://nordicapis.com/12-frameworks-to-build-chatops-bots/ 

http://www.findbestopensource.com/tagged/chatbot

**Comment by kyyberi** [comment]
Looks promising https://github.com/akapribot/kutkut

**Comment by kyyberi** [comment]
For NLP part we might want to consider https://wit.ai/faq It was recommended by one experienced bot developer. Supports even Finnish

**Comment by brylie** [comment]
[Node-RED](https://nodered.org) also has a [chat bot module](https://flows.nodered.org/node/node-red-contrib-chatbot).

**Comment by philippeluickx** [comment]
From my personal forage into this space and trying out a few, there's only 2 really good options to make something that works quickly.
- wit.ai (owned by Facebook)
- api.ai (owned by Google).

**Comment by bajiat** [comment]
@philippeluickx I quess this issue can be closed, right?

**Comment by philippeluickx** [comment]
Let's close it yes. There's an idea of migrating from api.ai to open source components in the future, but I'd rather see that happen after we validated the business case.
